instrumentation:
  root: lib
  excludes: ['logger.js']
  embed-source: true
  include-all-sources: true
reporting:
  reports:
    - lcov
    - text
  watermarks:
    statements: [90, 95]
    lines: [90, 95]
    functions: [90, 95]
    branches: [90, 95]
check:
  global:
    statements: 95
    lines: 95
    functions: 95
    branches: 95
